<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <PropertyGroup>
    <Description>Tests for Subatomix Testing Support Library</Description>
    <RootNamespace>Subatomix.Testing</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!-- Simulate .props import from package -->
  <Import Project="..\Subatomix.Testing\Subatomix.Testing.props" />

  <ItemGroup>
    <ProjectReference Include="..\Subatomix.Testing\Subatomix.Testing.csproj" />
    <ProjectReference Include="..\Subatomix.Testing.SqlServerIntegration\Subatomix.Testing.SqlServerIntegration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Data" />
    <Using Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>
