<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <PropertyGroup>
    <Description>Subatomix SQL Server Integration Testing Helper</Description>
    <PackageDescription>Easy temporary SQL Server databases for integration testing.</PackageDescription>
    <PackageTags>$(PackageTags) integration sql server database</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" PrivateAssets="none" />
    <PackageReference Include="Nullable"                 PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Data" />
    <Using Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>
