<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <PropertyGroup>
    <Description>Subatomix Testing Utilities</Description>
    <PackageDescription>Preferred dependencies and utilities for automated testing.</PackageDescription>
    <TargetFrameworks>net481;net6.0;net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ContentTargetFolders>build</ContentTargetFolders>
  </PropertyGroup>

  <!-- Simulate .props import from package -->
  <Import Project="Subatomix.Testing.props" />

  <ItemGroup>
    <PackageReference Include="coverlet.collector"     PrivateAssets="none" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="none" />
    <PackageReference Include="Moq"                    PrivateAssets="none" />
    <PackageReference Include="NUnit"                  PrivateAssets="none" />
    <PackageReference Include="NUnit3TestAdapter"      PrivateAssets="none" />
    <PackageReference Include="Shouldly"               PrivateAssets="none" />
  </ItemGroup>

  <!-- Undo things set by NuGet packages that would make this project unpackable -->
  <ItemGroup>
    <ProjectCapability Remove="TestContainer" />
  </ItemGroup>
  <PropertyGroup>
    <TestProject>false</TestProject>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <None     Remove="Subatomix.Testing.props" />
    <Content Include="Subatomix.Testing.props" />
  </ItemGroup>

</Project>
