<Project>

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <!--
    Imported early: Directory.Build.props -> this -> SDK .props -> project
    https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build
  -->

  <ItemGroup>
    <Using Include="Moq" />
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
    <Using Include="Subatomix.Testing" />
  </ItemGroup>

</Project>
