<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <PropertyGroup>
    <Description>Subatomix Testing Utilities</Description>
    <PackageDescription>Preferred dependencies and utilities for automated testing.</PackageDescription>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ContentTargetFolders>build</ContentTargetFolders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"                    PrivateAssets="none" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" PrivateAssets="none" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport"    PrivateAssets="none" />
    <PackageReference Include="Moq"                                       PrivateAssets="none" />
    <PackageReference Include="NUnit"                                     PrivateAssets="none" />
    <PackageReference Include="NUnit3TestAdapter"                         PrivateAssets="none" />
    <PackageReference Include="Shouldly"                                  PrivateAssets="none" />
  </ItemGroup>

  <!-- Undo things set by NuGet packages that would make this project unpackable -->
  <ItemGroup>
    <ProjectCapability Remove="TestContainer" />
    <Content Remove="@(Content->WithMetadataValue('Link', 'testhost.exe'))" />
    <Content Remove="@(Content->WithMetadataValue('Link', 'testhost.dll'))" />
    <Content Remove="@(Content->WithMetadataValue('Link', 'testhost.x86.exe'))" />
    <Content Remove="@(Content->WithMetadataValue('Link', 'testhost.x86.dll'))" />
  </ItemGroup>
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <None     Remove="Subatomix.Testing.props" />
    <Content Include="Subatomix.Testing.props" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Moq" />
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
